#!/usr/bin/env bash

function macosx(){
	wget https://github.com/YGoldking/Daily-Framework/releases/download/v1.0.0/MacOSX-Sierra-Gtk_20180509.deb
	sudo dokg -i MacOSX-Sierra-Gtk_20180509.deb
	sudo apt -f install -y 
	echo "安装完成................."
}

function desktop(){
	echo -e """
	$xcyan 1)$xgreen ✔  MacOSX-Sierra
	$xcyan 2)$xgreen ✔  LSY-Alien-[(外星人主题)开发中......]
	$xcyan 3)$xgreen ✔  更多......
	$xcyan 0)$xred ✘  返回 ◀◀
	"""
	echo -n -e "${cyan}选择主题: $red"
	read -e themes
	case $themes in
		1 )
		macosx
			;;
		* )
		echo " "
			;;
	esac
}