#!/usr/bin/env bash

function tor-install(){
echo "下载安装包..................."
wget http://www.theonionrouter.com/dist/torbrowser/7.5.4/tor-browser-linux64-7.5.4_zh-CN.tar.xz
echo "解压tor-browser..................."
tar xvf tor-browser-linux64-7.5.4_zh-CN.tar.xz
echo "移至 /opt/ ..................."
sudo mv tor-browser_zh-CN /opt/
echo "创建桌面文件................"
cat>start-tor-browser.desktop<<EOF
[Desktop Entry]
Type=Application
Name=Tor Browser
GenericName=Web Browser
Comment=Tor Browser is +1 for privacy and -1 for mass surveillance
Categories=Network;WebBrowser;Security;
Exec=sh -c '"/opt/tor-browser_zh-CN/Browser/start-tor-browser" --detach || ([ !  -x "/opt/tor-browser_zh-CN/Browser/start-tor-browser" ] && "$(dirname "$*")"/Browser/start-tor-browser --detach)' dummy %k
X-TorBrowser-ExecShell=./Browser/start-tor-browser --detach
Icon=/opt/tor-browser_zh-CN/Browser/browser/icons/mozicon128.png
StartupWMClass=Tor Browser
EOF
sudo mv start-tor-browser.desktop /usr/share/applications/
echo "删除软件包.................."
rm tor-browser-linux64-7.5.4_zh-CN.tar.xz
echo "安装完成........................"
}

if [[ ! -d "/opt/tor-browser_zh-CN" ]]; then
	tor-install
else
	echo "已安装.................."
fi
