#!/usr/bin/env bash

function wine-wechat(){
	echo "自己打包的deb没地方存放，各位自行下载吧............"
	echo "请在 十秒 内复制链接："
	echo "https://pan.baidu.com/s/10uSBJkp30BifYa3taexoDw"
	sleep 10
}

function deepin-wechat(){
	sudo dpkg --add-architecture i386
	sudo cp -r ./public/deepin-key/etc/apt/sources.list.d/deepin.list /etc/apt/sources.list.d/
	sudo cp -r ./public/deepin-key/etc/apt/trusted.gpg.d/deepin-archive-keyring.gpg /etc/apt/trusted.gpg.d/
	sudo cp -r ./public/deepin-key/etc/apt/trusted.gpg.d/deepin-pools-keyring.gpg /etc/apt/trusted.gpg.d/
	sudo cp -r ./public/deepin-key/usr/share/keyrings/deepin-archive-keyring.gpg /usr/share/keyrings/
	sudo apt-get update && sudo apt-get install deepin.com.wechat -y
	sudo rm -rf /etc/apt/sources.list.d/deepin.list
	sudo rm -rf /etc/apt/trusted.gpg.d/deepin-archive-keyring.gpg
	sudo rm -rf /etc/apt/trusted.gpg.d/deepin-pools-keyring.gpg
	sudo rm -rf /usr/share/keyrings/deepin-archive-keyring.gpg
	echo "安装完成...................."
}

function wechat(){
	echo -e """
	$xcyan 1)$xgreen ✔  微信(wine)	
	$xcyan 2)$xgreen ✔  deepin-微信	
	$xcyan 3)$xgreen ✔  待添加......
	$xcyan 0)$xred ✘  返回 ◀◀
	"""
	echo -n -e "${cyan}请选择版本 *) ：$red"
	read -e qqinstall
	case $qqinstall in
		1 )
		wine-wechat
			;;
		2 )
		deepin-wechat
			;;
		* )
		echo " "
			;;
	esac
}
wechat